Numpy added to install

diff --git a/sequre b/sequre
--- a/sequre
+++ b/sequre
@@ -1,23 +1,47 @@
 #!/usr/bin/env bash
 
-echo "Setting up Sequre ..."
-
 export PID=$2
-SEQURE_STDLIB=$SEQURE_PATH/stdlib/sequre
-
-if [[ "$OSTYPE" == "linux-gnu"* ]]; then
-    export CP_OPTIONS=-uf
-elif [[ "$OSTYPE" == "darwin"* ]]; then
-    export CP_OPTIONS=-f
+if [[ -z "${SEQURE_CODON_PATH}" ]]; then
+    echo "Error! SEQURE_CODON_PATH env variable not set" >&2
+    return
 fi
 
-if [[ ${*:3} == *"--local"* ]]; then
-    cp $CP_OPTIONS $SEQURE_STDLIB/network/unix_socket.codon $SEQURE_STDLIB/network/socket.codon
-else
-    cp $CP_OPTIONS $SEQURE_STDLIB/network/inet_socket.codon $SEQURE_STDLIB/network/socket.codon
+if [[ -z "${SEQURE_SEQ_PATH}" ]]; then
+    echo "Error! SEQURE_SEQ_PATH env variable not set" >&2
+    return
 fi
 
-echo "Compiling $1 ..."
-echo "Seq plugin searched at $SEQ_PATH ..."
-echo "Sequre plugin searched at $SEQURE_PATH ..."
-GC_INITIAL_HEAP_SIZE=8179869184 GC_LIMIT=8179869184 codon run -plugin $SEQURE_PATH -plugin $SEQ_PATH -release $1 ${*:3}
+if [[ -z "${SEQURE_NUMPY_PATH}" ]]; then
+    echo "Error! SEQURE_NUMPY_PATH env variable not set" >&2
+    return
+fi
+
+if [[ -z "${SEQURE_PATH}" ]]; then
+    echo "Error! SEQURE_PATH env variable not set" >&2
+    return
+fi
+
+if [ ! -d "${SEQURE_CODON_PATH}/install" ]
+then
+    echo "Codon not installed at ${SEQURE_CODON_PATH}" >&2
+    return
+fi
+
+if [ ! -d "${SEQURE_SEQ_PATH}/install" ]
+then
+    echo "Seq-lang not installed at ${SEQURE_SEQ_PATH}" >&2
+    return
+fi
+
+if [ ! -d "${SEQURE_NUMPY_PATH}/build" ]
+then
+    echo "Codon-numpy not installed at ${SEQURE_NUMPY_PATH}" >&2
+    return
+fi
+
+echo "Codon found at $SEQURE_CODON_PATH"
+echo "Seq-lang plugin found at $SEQURE_SEQ_PATH"
+echo "Numpy plugin found at $SEQURE_NUMPY_PATH"
+echo "Sequre plugin found at $SEQURE_PATH"
+echo "Compiling $1 in -release mode at CP$2 ..."
+GC_INITIAL_HEAP_SIZE=8179869184 $SEQURE_CODON_PATH/build/codon run -plugin $SEQURE_PATH -plugin $SEQURE_SEQ_PATH -plugin $SEQURE_NUMPY_PATH -release $1 ${*:3}
